### ISSUE TITLE
Gilneas (New in 1.17.0)

### ISSUE THREAD

**Issue by fleimgruber** [shagu/pfQuest-turtle#103]
Are there any plans to update pfQuest for the new content in https://forum.turtle-wow.org/viewtopic.php?t=5391?

**Comment by shagu** [comment]
as soon as i receive the database

**Comment by Husmeador12** [comment]
> as soon as i receive the database

Now it is open the database  https://database.turtle-wow.org/?quests#0+7+1+2

**Comment by shagu** [comment]
Good to know, but that doesn't help. What I need for pfQuest-turtle is an SQL-dump of their database, like the last time.
As soon as the turtle-wow staff wants to have an updated pfQuest for their community, they can send it to me and I will take care of building a new release. While that's not the case, there's nothing I can do.

**Comment by fleimgruber** [comment]
FYI, AtlasLoot mentions 27th of October: https://github.com/Lexiebean/AtlasLoot#readme

**Comment by shagu** [comment]
I received a database dump yesterday night and have updated pfQuest-turtle accordingly.
I didn't had much time to test yet, but after a quick check everything seems fine :)

Fixed via: https://github.com/shagu/pfQuest-turtle/commit/e405f1a5f4ac8cfcc863a9923b7688ef7eb9c562
