### ISSUE TITLE
New quests in 1.17.0

### ISSUE THREAD

**Issue by Lichbanez** [shagu/pfQuest-turtle#105]
Hi, is there a way to distinguish the new quests added in this update from the old ones by any chance? I can't find a list or a way to sort the database for them and I'd like not to check every zone manually.
Thanks.

**Comment by shagu** [comment]
Hi, no sorry there isn't. Maybe the turtle-database has something like that, or a changelog?

**Comment by Lichbanez** [comment]
No it doesn't unfortunately, thanks again.
