### ISSUE TITLE
[Feature Request] Update the pfQuest-turtle database to patch 1.17.1 of Turtle WoW

### ISSUE THREAD

**Issue by EyeOfTheBeast** [shagu/pfQuest-turtle#112]
This Turtle WoW 1.17.1 patch has just been released today with a bunch of new quests, units, objects and items that aren't in the current pfQuest-turtle version.

**Comment by shagu** [comment]
There's nothing I can do as long as I don't receive the required data.
I already asked the staff, but got no response yet. So we have to wait until they decide to send me the database.

The process would be the same as for https://github.com/shagu/pfQuest-turtle/issues/103

**Comment by shagu** [comment]
I received the database and start working on it now :)
