### ISSUE TITLE
Quest [Old Bryan's Food Delivery] is missing

### ISSUE THREAD

**Issue by Plan414** [shagu/pfQuest-turtle#53]
This quest and all units associated are missing from the addon.

https://database.turtle-wow.org/?quest=40413

**Comment by Gurky-Kronos** [comment]
I'll fix it if it's fixable when I update for the next patch

**Comment by Gurky-Kronos** [comment]
> This quest and all units associated are missing from the addon.
> 
> https://database.turtle-wow.org/?quest=40413

Should be fixed now
