### ISSUE TITLE
Quests 80261-80265

### ISSUE THREAD

**Issue by WarMEN3** [shagu/pfQuest-turtle#58]
Qests 80261-80265 have incorrect coordinates of inspection points.
Looks like the coordinates are for Stormwind without a port.

**Comment by Gurky-Kronos** [comment]
@WarMEN3 can you provide me the correct cords to the npcs/object etc and ill correct them.

**Comment by shagu** [comment]
With the latest update, it should now contain everything from the turtle-wow database.
The current state of data was obtained by @Haaxor1689 who has access to the internal turtle-wow database.
