### ISSUE TITLE
Quest The Harvest Golem Mystery XIII Cords

### ISSUE THREAD

**Issue by Hiethen** [shagu/pfQuest-turtle#62]
Quest is doesn't show cords for "Lordaeron Stamped Crate" at 20.9, 36.0. @Gurky-Turtle 
https://database.turtle-wow.org/?quest=40482

**Comment by shagu** [comment]
With the latest update, it should now contain everything from the turtle-wow database.
The current state of data was obtained by @Haaxor1689 who has access to the internal turtle-wow database.
