### ISSUE TITLE
Custom quests not displaying on map

### ISSUE THREAD

**Issue by rogerbest40** [shagu/pfQuest-turtle#64]
For example the quest of the sheeps in elwyn forest, wouldnt be tracked on map even tho in database of addon i could specificly select the sheeps to be tracked and it even tracked the many kinds of sheep including the one needed for the quest that was a special one (friendly target).

Im using latest version of both pfquest and tw mod for it.

**Comment by Gurky-Turtle** [comment]
https://database.turtle-wow.org/?quest=60005

**Comment by Gurky-Turtle** [comment]
https://github.com/shagu/pfQuest-turtle/pull/65
