### ISSUE TITLE
[BUG] The Harvest Golem Mystery

### ISSUE THREAD

**Issue by nichlasmm** [shagu/pfQuest-turtle#66]
https://database.turtle-wow.org/?quest=40470

This questchain doesnt show properly in both pfQuest and on map.

It only shows directions and logs for the first chain quest

**Comment by shagu** [comment]
The problem here is, that all have the same quest title.

As there are no quest-ids available in vanilla, pfQuest tries to identify a quest-id based on titles, quest-level, quest-race and quest-class requirements. As they are all the same on that chain, it fails to detect the proper quest-id.

**Comment by shagu** [comment]
The quest-id detection works. But the data was faulty. It looks like turtle-wow renamed some quests.
It's fixed now via this commit: https://github.com/shagu/pfQuest-turtle/commit/ca1f5e719d74b10a0f8ae292ae27e1a4a6121eb3
