### ISSUE TITLE
Reports of Dustwallow objectives missing

### ISSUE THREAD

**Issue by zeress** [shagu/pfQuest-turtle#78]
Quest ID: [40415](https://database.turtle-wow.org/?quest=40415)

The quest does not track where to go. It requires interacting with two NPCs

1. [60729](https://database.turtle-wow.org/?npc=60729), giving [60602](https://database.turtle-wow.org/?item=60602)
2. [60730](https://database.turtle-wow.org/?npc=60730), giving [60603](https://database.turtle-wow.org/?item=60603)

Outside of this, the quest tracking works correctly as obtaining both reports correctly points you back to the turn in.

**Comment by Gurky-Turtle** [comment]
Quest reports everything correctly but it looks like the items are not linked to anything:
  [40415] = {
    ["end"] = {
      ["U"] = { 60727 },
    },
    ["lvl"] = 37,
    ["min"] = 32,
    ["obj"] = {
      ["I"] = { 60602, 60603 },
    },
    ["start"] = {
      ["U"] = { 60727 },
    },
  },
  
 Items:

  [60602] = {},
  [60603] = {},
  
 So the items need to look like this:
 
  [60602] = {
    ["U"] = {
      [60729] = 100,
    },
  },
  [60603] = {
    ["U"] = {
      [60730] = 100,
    },
  },
