### ISSUE TITLE
The Lost Bet does not show where to hand in

### ISSUE THREAD

**Issue by zeress** [shagu/pfQuest-turtle#79]
Quest ID: [55202](https://database.turtle-wow.org/?quest=55202)

This quest seems to not indicate where to hand it in, which is to NPC [52068](https://database.turtle-wow.org/?npc=52068)

**Comment by Gurky-Turtle** [comment]
Looks like its missing cords:

  [52068] = {
    ["coords"] = {},
    ["fac"] = "A",
    ["lvl"] = "20-38",
  },
  
  Should be
  [52068] = {
    ["coords"] = {
      [1] = { 21.0, 71.3, 11, 120 },
    },
    ["fac"] = "A",
    ["lvl"] = "20-38",
  },
