### ISSUE TITLE
The Shield's Owner not tracking objectives

### ISSUE THREAD

**Issue by zeress** [shagu/pfQuest-turtle#80]
Quest ID: [40554](https://database.turtle-wow.org/?quest=40554)

The quest does not track where to go. It requires interacting with three NPCs

1. [60949](https://database.turtle-wow.org/?npc=60949)
2. [60950](https://database.turtle-wow.org/?npc=60950)
3. [60951](https://database.turtle-wow.org/?npc=60951)

Outside of this, the quest tracking works correctly as obtaining all reports correctly points you back to the turn in.

**Comment by Gurky-Turtle** [comment]
[40554] = {
    ["end"] = {
      ["U"] = { 4944 },
    },
    ["lvl"] = 35,
    ["min"] = 30,
    ["obj"] = {
      ["U"] = { 60385, 60386, 60387 },
    },
    ["pre"] = { 40553 },
    ["start"] = {
      ["U"] = { 4944 },
    },
  },
  
  Wrong Units assigned, should be:

  [40554] = {
    ["end"] = {
      ["U"] = { 4944 },
    },
    ["lvl"] = 35,
    ["min"] = 30,
    ["obj"] = {
      ["U"] = { 60949, 60950, 60951 },
    },
    ["pre"] = { 40553 },
    ["start"] = {
      ["U"] = { 4944 },
    },
  },
