### ISSUE TITLE
"Into the Uplands" does not track turn-in NPC

### ISSUE THREAD

**Issue by zeress** [shagu/pfQuest-turtle#81]
Quest ID: [40080](https://database.turtle-wow.org/?quest=40080)

This quest seems to not indicate where to hand it in, which is to NPC [91713](https://database.turtle-wow.org/?npc=91713)

**Comment by Gurky-Turtle** [comment]
[91713] = {
    ["coords"] = {},
    ["fac"] = "H",
    ["lvl"] = "30",
  },
  
  Looks like the npc is missing cords. 
  
  Should be
  
    [91713] = {
    ["coords"] = { 39.8, 5.0, 130, 300 },
    ["fac"] = "H",
    ["lvl"] = "30",
  },
