### ISSUE TITLE
Incorrect position marker for Angus Stern

### ISSUE THREAD

**Issue by zeress** [shagu/pfQuest-turtle#84]
Angus Stern seems to be erroneously listed as being located at around 41 89 in SW, instead of his actual location of 51.8 93.6. Perhaps this was his location in SW before the Harbor?

NPC: [Angus Stern - 1141](https://database.turtle-wow.org/?npc=1141)

**Comment by Gurky-Turtle** [comment]
[1141] = {
    ["coords"] = {
      [1] = { 41.5, 89.4, 1519, 30 },
    },
    ["fac"] = "A",
    ["lvl"] = "60",
  },
