### ISSUE TITLE
Sailors Innovation does not track Objective

### ISSUE THREAD

**Issue by zeress** [shagu/pfQuest-turtle#87]
Quest: [40142](https://database.turtle-wow.org/?quest=40142)

While the quest correctly tracks the kill trackers for the Juicy Crawler Legs, it does not track the Pinch of Salt.

You can acquire item [60207](https://database.turtle-wow.org/?item=60207) from NPC [Chef Jenkel - 91950](https://database.turtle-wow.org/?npc=91950)

NOTE: Chef Jenkel's name does not seem to properly appear on the database, but this ID comes up for his name when searching

**Comment by Gurky-Turtle** [comment]
[60207] = {
    ["U"] = {
      [91950] = 100,
    },
  },
