### ISSUE TITLE
Southsea Reserves does not track objective

### ISSUE THREAD

**Issue by zeress** [shagu/pfQuest-turtle#88]
Quest: [40418](https://database.turtle-wow.org/?quest=40148)

The quest is lacking the reference for the item [60217](https://database.turtle-wow.org/?item=60217). It is acquired from the NPC [92137](https://database.turtle-wow.org/?npc=92137) via interaction.

**Comment by Gurky-Turtle** [comment]
[60217] = {
    ["U"] = {
      [92137] = 100,
    },
  },
