### ISSUE TITLE
Crumbling Allies missing tracking on one objective

### ISSUE THREAD

**Issue by zeress** [shagu/pfQuest-turtle#89]
Quest: [40176](https://database.turtle-wow.org/?quest=40176)
Item: [60250](https://database.turtle-wow.org/?item=60250) at a 10% chance

The quest Crumbling Allies is missing the tracking for only item 60250, off of NPC 40176. with a drop chance of 10%

**Comment by Gurky-Turtle** [comment]
[60248] = {
    ["U"] = {
      [91827] = 30,
      [91825] = 30,
      [91819] = 30,
      [91960] = 30,
      [91961] = 30,
    },
  },
  [60249] = {
    ["U"] = {
      [92203] = 30,
    },
  },
  [60250] = {
    ["U"] = {
      [91966] = 10,
    },
  },

**Comment by zeress** [comment]
Confirmed fixed as of the most recent DB update
